#!/usr/bin/env bash

export PATH="node_modules/.bin:$PATH"

main() {
  webpack-dev-server --inline --hot
}

build() {
  webpack -p
  cp -r src/{index.html,assets} build
}

test() {
  jest --watch
}

case "$1" in
  "" ) main ;;
  b | build ) build ;;
  t | test ) test ;;
esac
